# Generated by Django 2.2 on 2020-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RmspQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('OGRN', 'ОГРН'), ('INN', 'ИНН')], max_length=4, verbose_name='Тип документа')),
                ('document_number', models.BigIntegerField(verbose_name='Номер документа')),
                ('is_msp', models.BooleanField(verbose_name='Является ли субъект представителем малого или среднего предпринимательства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
